- server/plugins/router.js
- server/routes/target-areas-within-station-buffer.js
- server/routes/warnings-alerts-within-station-buffer.js
- server/services/index.js
- server/services/queries.json
- test/services/index.js
PI2: Station page - alert or warning issued
https://eaflood.atlassian.net/browse/FIS-373
Create service to calculate target areas within 8km of a station
> FIS-373: Add getTargetAreasWithinStationBuffer service.

- server/services/queries.json
PI2: Station Page - list view upon selecting an alert/warning/severe warning
https://eaflood.atlassian.net/browse/FIS-609
Return extra column data in getWarningsAlertsWithinStationBuffer query for filtering of alerts-and-warnings page.
> FIS-609: Return extra columns in getWarningsAlertsWithinStationBuffer

- package-lock.json
- package.json
Target Area Updates - Aug 2021
https://eaflood.atlassian.net/browse/FS-96
https://eaflood.atlassian.net/browse/FS-97
https://eaflood.atlassian.net/browse/FSR-406
Update service version numbers for Target Area Updates.
> FS-96/FS-97/FSR-406: Target Area Updates Aug 2021

- package-lock.json
- package.json
> release 5.5.0 prep

- package-lock.json
- package.json
Target Area Update - 2 March 2022
https://eaflood.atlassian.net/browse/FSR-530
Update version number to 5.6.0.
> FSR-530: Update version number forTA Release 03-2022.

- server/routes/index.js
Target Area Update - 2 March 2022
https://eaflood.atlassian.net/browse/FSR-530
Fix sonarcloud error raised during initial merge of branch which updates version number of flood-service.
> Fix sonarcloud error during change of version for TA update.

- package-lock.json
- package.json
- server/routes/index.js
Target Area Update - 2 March 2022
https://eaflood.atlassian.net/browse/FSR-530
Merge master branch into development branch for version update to 5.6.0
> Update version number from TA update release

- package-lock.json
- package.json
CFF - Release 5.7.0 version number update.
https://eaflood.atlassian.net/projects/FSR/versions/15905/tab/release-report-all-issues
> CFF - Release 5.7.0 version number update.

- package-lock.json
- package.json
Update version numbers to 5.8.0
> Release 5.8.0: Update version numbers.

- package-lock.json
- package.json
Release 5.8.0: Update version number only in package files.
See https://eaflood.atlassian.net/secure/ReleaseNote.jspa?projectId=13459&version=15907 for changes to flood-app repo.
> Release 5.8.0

- package-lock.json
- package.json
Release 5.11.0 version update.
https://eaflood.atlassian.net/projects/FSR/versions/16032/tab/release-report-all-issues
Tickets included in this release:
FSR-599 Update link to NRW site for Welsh stations
> Release 5.11.0 version update.

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16082/tab/release-report-all-issues
> Prep release 5.12.0

- package-lock.json
- package.json
- Release 5.12.1
- Add release notes and update version number
> prep release.5.12.1

- server/routes/river-name.js
- server/services/index.js
- server/services/queries.json
- test/routes/happy-routes.js
- test/routes/sad-routes.js
- Move like %'s out of route handler and into query
- Pluralise service name to better reflect behaviour
> Move SQL from route to query

- server/services/index.js
- server/services/queries.json
https://eaflood.atlassian.net/browse/FSR-587
Move the regex word boundaries to the SQL statement as doing them in the code broke the river synonyms exclusions
> Fix: river exclusion terms

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16104/tab/release-report-all-issues
> Release 5.13.0

- package-lock.json
> Fix reported vulnerabilities

- package-lock.json
- server/plugins/router.js
- server/routes/river-name.js
- server/routes/river.js
- server/services/index.js
- server/services/queries.json
- test/routes/happy-routes.js
- test/routes/sad-routes.js
- test/services/index.js
* Rivers search feature 
* Resolve vulnerabilities
> Merge development into test

- package-lock.json
- package.json
- server/plugins/router.js
- server/routes/river-name.js
- server/routes/river.js
- server/services/index.js
- server/services/queries.json
- test/routes/happy-routes.js
- test/routes/sad-routes.js
- test/services/index.js
https://eaflood.atlassian.net/projects/FSR/versions/16012/tab/release-report-all-issues
> Release 6.0.0

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16105/tab/release-report-all-issues
> Release 6.1.0

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16336/tab/release-report-all-issues
> Release 6.2.0

- server/routes/station-threshold.js
- server/services/index.js
- server/services/queries.json
- test/routes/happy-routes.js
- test/services/index.js
* Add direction to DB query and service call signature
* Refactored route to remove code duplication and use declarative style
* fix broken tests
> Add direction to thresholds endpoint

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16485/tab/release-report-all-issues
> Bump version number to 6.6.1

- package-lock.json
- package.json
https://eaflood.atlassian.net/projects/FSR/versions/16565/tab/release-report-all-issues
> Bump version number to 6.7.0

- .github/dependabot.yml
- package-lock.json
Dependency Updates
https://eaflood.atlassian.net/browse/FSR-776
> FSR-776 Dependency Updates

- package-lock.json
- package.json
- server/services/db.js
- server/util.js
Updates the following packages to the latest versions:
-    "@hapi/boom": "10.0.1",
-    "@hapi/code": "^9.0.3",
-    "@hapi/hapi": "^21.3.2",
-    "pg": "8.11.2",
-    "proxy-agent": "6.3.0",
-    "sinon": "^15.2.0",
-    "standard": "17.1.0",
> FSR-1007 - dependencies updates

- package-lock.json
- package.json
merge release 7.4.0 into master
> merge release 7.4.0 into master

- server/services/index.js
- server/services/queries.json
- test/services/index.js
https://eaflood.atlassian.net/browse/FSR-965
> FSR- 965 | IMTD Logic changes

- package-lock.json
- package.json
- https://eaflood.atlassian.net/projects/FSR/versions/16929/tab/release-report-all-issues
> Release 7.8.0

- package-lock.json
- package.json
- readme.md
- Introduces the dotenv and nodemon package for streamlined environment variable management from a .env file.
- Improves security by excluding the .env file from version control.
- Updates package.json and the README.md with usage instructions.
> FSR-1145 | Introduce dotenv and nodemon

- .github/workflows/merge.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- release-docs/lib/create-release-notes.js
- release-docs/template.njk
Add workflows for:
* creating release branch and PR's for merging the release branch into development and master
* merging the release branch in and creating a github release
> FSR-1170 | Add release workflow

- package-lock.json
- package.json
- release-docs/CFF-8.3.0.md
> Release 8.3.0

- package-lock.json
- package.json
- release-docs/CFF-8.4.0.md
> Release 8.4.0

- package-lock.json
- package.json
- release-docs/CFF-8.5.0.md
> Release 8.5.0

- package-lock.json
- package.json
https://eaflood.atlassian.net/jira/software/c/projects/FSR/boards/1320
> FSR-1251 | npm Updates

- package-lock.json
- package.json
- release-docs/CFF-8.6.0.md
> Release 8.6.0

- package-lock.json
- package.json
- release-docs/CFF-8.8.0.md
> Release 8.8.0

- package-lock.json
- package.json
- release-docs/CFF-8.9.0.md
> Release 8.9.0

- package-lock.json
- package.json
- release-docs/CFF-8.10.0.md
> Release 8.10.0

- package-lock.json
- package.json
Reverts DEFRA/flood-service#269
> Revert "FSR-1344 | NPM package updates for service"

- package.json
Reverts DEFRA/flood-service#273
> Revert "test"

- package-lock.json
- package.json
- release-docs/CFF-8.11.0.md
> Release 8.11.0

- .github/workflows/ci.yml
- **FSR-1378 | fix sonarcloud issue**
- **Switch away from deprecated github action to recommended action**
> FSR-1378 | fix sonarcloud issue

- .github/workflows/ci.yml
- package-lock.json
- package.json
- release-docs/CFF-8.12.0.md
> Release 8.12.0

- package-lock.json
- package.json
- release-docs/CFF-8.13.0.md
> Release 8.13.0

- package-lock.json
- package.json
- release-docs/CFF-8.14.0.md
> Release 8.14.0

- server/config.js
- server/routes/index.js
- server/routes/stations-by-radius.js
Issues highlighted by sonarcloud quality gate
> FSR-1324 : sonar cloud issue

- package-lock.json
- package.json
- release-docs/CFF-8.15.0.md
- release-docs/template.njk
> Release 8.15.0

- package-lock.json
- package.json
- release-docs/CFF-8.18.0.md
> Release 8.18.0

- package-lock.json
- package.json
- release-docs/CFF-8.19.0.md
> FSR-1508 | Release 8.19.0
